#ifndef REDUX_REVISION_HPP
#define REDUX_REVISION_HPP

namespace redux {

    /*!  @file      revision.hpp
     *   @brief     Constants containing the version numbers and revision details of the library.
     *   @name      Version/Revision information
     *   @details   These constants are auto-generated by cmake/git and placed in the \c revision.cpp file.
     *              The version numbers will be extracted from the latest \em annotated label in the git-tree,
     *              and the revision-status will contain the latest commit message (and a tag "Modified" if
     *              the git-tree contains un-commited modifications).
     *
     *   @author    Tomas Hillberg (hillberg@astro.su.se)
     *   @date      2013
     */

    extern const int reduxVersionMajor;       //!< Major version
    extern const int reduxVersionMinor;       //!< Minor version
    extern const int reduxVersionPatch;       //!< Patch version
    extern const int reduxVersionCommit;      //!< Number of commits since last version-tag
    extern const char* reduxCommitMessage;    //!< Commit message of the last commit
    extern const char* reduxCommitTime;       //!< Commit timestamp
    extern const char* reduxBuildTime;        //!< Compilation timestamp

}

#endif // REDUX_REVISION_HPP
